apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak

resources:
  - deployment.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - externalsecret-admin.yaml
  - externalsecret-oidc-clients.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml

commonLabels:
  app.kubernetes.io/component: identity-provider
  app.kubernetes.io/part-of: a2-stack

replicas:
  - name: keycloak
    count: 2

images:
  - name: quay.io/keycloak/keycloak
    newName: quay.io/keycloak/keycloak
    newTag: "23.0.1"

configMapGenerator:
  - name: keycloak-realm-config
    files:
      - realm-import/realm.json