apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - autoscaling.yaml

commonLabels:
  app.kubernetes.io/name: mcp-orchestrator-api
  app.kubernetes.io/component: api